version: '3.3'
services: 
    master: 
        image: labulaka522/crocodile
        container_name: crocodile_master
        restart: always
        ports: 
          - 8080:8080
        volumes: 
          - $PWD/core_docker.toml:/app/core.toml
        depends_on:
          - mysql
          - redis
    worker:
        image: labulaka522/crocodile:worker
        container_name: crocodile_worker
        volumes: 
            - $PWD/core_docker.toml:/app/core.toml
        depends_on:
          - master
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: "crocodile"
            MYSQL_DATABASE: "crocodile"
        # volumes: 
        #   - "/data:/usr/lib/mysql"   # mysql数据持久化
        ports: 
          - 3306:3306
    redis:
        image: redis:latest
        restart: always
        ports: 
          - 6379:6379