on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Build_release


env:
  IMAGE_NAME: labulaka522/crocodile

jobs:
  build:
    name: Build And Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release ${{ github.ref }}
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Build All Release
        run: |
          make frontend
          make bindata
          make clean
          make vet
          make swag
          make build_all
      - name: Push Docker
        run: |
          echo ${{ secrets.DOCKER_PASSWORD}} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t $IMAGE_NAME . -f Dockerfile
          docker build -t $IMAGE_NAME:worker . -f Dockerfile.worker
          docker push IMAGE_NAME
          docker push $IMAGE_NAME:worker
      - name: Upload file to release
        uses: labulaka521/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
